# SPDX-License-Identifier: AGPL-3.0-or-later
defmodule SukhiFedi.AP.Published do
  @moduledoc """
  Carry a mirrored remote note's *origin* publish time onto its
  `notes.created_at`.

  Every path that mirrors a remote object — the inbox `Create`, the
  thread/quote back-fill (`NoteFetcher`), and inbound DMs — used to let
  `created_at` default to the insert time. For a live post that's within
  seconds of the real `published`, so it goes unnoticed; but a
  back-filled thread fetches old posts *now*, so every ancestor showed
  today's date. Stamping the AP `published` fixes the displayed time
  (the Mastodon view reads `created_at` directly).

  `created_at` is an autogenerated `timestamp` (`:utc_datetime`), so we
  set it with `put_change` — Ecto only fills timestamps that aren't
  already in the changeset, so an explicit value wins. A missing or
  unparseable `published` leaves the changeset alone and Ecto's
  insert-time default applies.
  """

  @doc "The object's `published` as a second-precision `DateTime`, or `nil`."
  @spec at(map()) :: DateTime.t() | nil
  def at(%{"published" => ts}) when is_binary(ts) do
    case DateTime.from_iso8601(ts) do
      {:ok, dt, _offset} -> DateTime.truncate(dt, :second)
      _ -> nil
    end
  end

  def at(_), do: nil

  @doc "Stamp `created_at` from the object's `published`, when present."
  @spec stamp(Ecto.Changeset.t(), map()) :: Ecto.Changeset.t()
  def stamp(changeset, object) do
    case at(object) do
      nil -> changeset
      dt -> Ecto.Changeset.put_change(changeset, :created_at, dt)
    end
  end
end
