# Kamal 2.x — Deno image build and push only (generated by Terraform — do not edit by hand)
#
# This file does NOT deploy anything. It exists solely to build the Deno image
# and push it to OCIR so config/deploy.yml can reference it as an accessory.
#
# Usage:
#   kamal build push --config-file config/deploy_deno.yml
#
# After pushing, reload the accessory on the server:
#   kamal accessory reboot deno

service: sukhi-fedi-deno

image: ${tenancy_namespace}/sukhi-fedi-deno

# Kamal requires at least one server entry even for build-only configs
servers:
  - ${public_ip}

registry:
  server: ${region}.ocir.io
  username:
    - OCIR_USERNAME
  password:
    - OCIR_AUTH_TOKEN

builder:
  arch: arm64
  context: deno
  dockerfile: deno/Dockerfile
  remote: ssh://deploy@${public_ip}

ssh:
  user: deploy
