# Kamal 2.x — Primary deployment (generated by Terraform — do not edit by hand)
# Manages: Elixir web service + PostgreSQL, NATS, Deno accessories
#
# First deploy:
#   kamal build push --config-file config/deploy_deno.yml  # push Deno image first
#   kamal setup
#   kamal accessory boot postgres
#   kamal accessory boot nats
#   kamal accessory boot deno
#   kamal accessory boot otelcol
#   kamal accessory boot jaeger
#   kamal accessory boot prometheus
#   kamal accessory boot grafana
#   kamal accessory boot cloudflared
#   kamal app exec --interactive --reuse "bin/sukhi_fedi eval 'SukhiFedi.Release.migrate()'"
#
# Subsequent:
#   kamal deploy

service: sukhi-fedi

image: ${tenancy_namespace}/sukhi-fedi-elixir

servers:
  web:
    - ${public_ip}

# ── Registry (OCIR) ───────────────────────────────────────────────────────────
registry:
  server: ${region}.ocir.io
  username:
    - OCIR_USERNAME
  password:
    - OCIR_AUTH_TOKEN

# ── Build ─────────────────────────────────────────────────────────────────────
# Builds natively on the ARM64 server — avoids slow QEMU cross-compilation
builder:
  arch: arm64
  context: elixir
  dockerfile: elixir/Dockerfile
  remote: ssh://deploy@${public_ip}

# ── kamal-proxy ───────────────────────────────────────────────────────────────
# SSL is disabled — Cloudflare Tunnel terminates TLS before traffic reaches here.
# cloudflared (host network) → localhost:80 (kamal-proxy) → app:4000
proxy:
  ssl: false
  host: ${domain}
  app_port: 4000

# ── Environment ───────────────────────────────────────────────────────────────
env:
  clear:
    MIX_ENV: prod
    PORT: "4000"
    DB_HOST: sukhi-fedi-postgres  # Docker DNS — Kamal 2 names accessories as {service}-{accessory}
    DB_NAME: sukhi_fedi
    DB_POOL_SIZE: "20"
    NATS_HOST: sukhi-fedi-nats    # Docker DNS — Kamal 2 names accessories as {service}-{accessory}
    NATS_PORT: "4222"
    DENO_URL: http://sukhi-fedi-deno:8000  # Docker DNS — Deno accessory internal HTTP
    OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4318
  secret:
    - DB_USER
    - DB_PASS

# ── SSH ───────────────────────────────────────────────────────────────────────
ssh:
  user: deploy

# ── Accessories ───────────────────────────────────────────────────────────────

accessories:
  postgres:
    image: postgres:16-alpine   # multi-arch — arm64 included
    roles:
      - web
    port: "127.0.0.1:5432:5432"  # loopback only, never public
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data

  nats:
    image: nats:2-alpine        # multi-arch — arm64 included
    roles:
      - web
    cmd: "--jetstream --store_dir /data --http_port 8222"
    volumes:
      - /mnt/data/nats:/data
    options:
      publish:
        - "127.0.0.1:4222:4222"  # loopback only

  deno:
    # Deno is an internal HTTP backend proxied by Elixir's ProxyPlug.
    # Port 8000 is NOT published — only reachable via Docker network DNS "deno".
    image: ${region}.ocir.io/${tenancy_namespace}/sukhi-fedi-deno
    roles:
      - web
    env:
      clear:
        NATS_URL: nats://sukhi-fedi-nats:4222
        PORT: "8000"
        OTEL_DENO: "1"
        OTEL_SERVICE_NAME: sukhi-fedi-deno
        OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4318

  cloudflared:
    # Cloudflare Tunnel — outbound-only connection to Cloudflare's edge.
    # Routes are configured in the Cloudflare Zero Trust dashboard:
    #   ${domain}              → http://host.docker.internal:80   (kamal-proxy)
    #   grafana.${domain}      → http://host.docker.internal:3000
    #   jaeger.${domain}       → http://host.docker.internal:16686
    # host-gateway lets cloudflared reach services bound to 127.0.0.1 on the host
    # without conflicting with the kamal Docker network.
    image: cloudflare/cloudflared:latest
    roles:
      - web
    cmd: "tunnel --no-autoupdate run"
    env:
      secret:
        - TUNNEL_TOKEN
    options:
      add-host: "host.docker.internal:host-gateway"

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    roles:
      - web
    cmd: "--config=/etc/otelcol-contrib/config.yaml"
    files:
      - config/otelcol/config.yaml:/mnt/data/otelcol/config.yaml
    volumes:
      - /mnt/data/otelcol/config.yaml:/etc/otelcol-contrib/config.yaml
    options:
      memory: 128m
      cpus: "0.25"

  jaeger:
    image: jaegertracing/all-in-one:latest
    roles:
      - web
    env:
      clear:
        COLLECTOR_OTLP_ENABLED: "true"
    options:
      publish:
        - "127.0.0.1:16686:16686"  # loopback only — tunnel via SSH to access
      memory: 256m
      cpus: "0.25"

  prometheus:
    image: prom/prometheus:latest
    roles:
      - web
    cmd: >-
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.enable-lifecycle
    files:
      - observability/prometheus/prometheus.yml:/mnt/data/prometheus/prometheus.yml
    volumes:
      - /mnt/data/prometheus/data:/prometheus
      - /mnt/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    options:
      publish:
        - "127.0.0.1:9090:9090"   # loopback only
      memory: 256m
      cpus: "0.25"

  grafana:
    image: grafana/grafana:latest
    roles:
      - web
    env:
      clear:
        GF_SERVER_ROOT_URL: https://${domain}/grafana
      secret:
        - GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - /mnt/data/grafana/data:/var/lib/grafana
      - /mnt/data/grafana/provisioning:/etc/grafana/provisioning
    options:
      publish:
        - "127.0.0.1:3000:3000"   # loopback only
      memory: 128m
      cpus: "0.25"
