# SPDX-License-Identifier: AGPL-3.0-or-later
defmodule SukhiFedi.Web.Router do
  use Plug.Router

  alias SukhiFedi.Web.InboxController
  alias SukhiFedi.Web.WebfingerController
  alias SukhiFedi.Web.NodeinfoController
  alias SukhiFedi.Web.ActorController
  alias SukhiFedi.Web.FeaturedController
  alias SukhiFedi.Web.CollectionController
  alias SukhiFedi.Web.NoteController
  alias SukhiFedi.Web.ViewerController
  alias SukhiFedi.Web.StatsController

  plug(Plug.Logger)
  plug(SukhiFedi.Web.AccessLogPlug)
  # Global per-peer rate limit. Conservative ceiling; internal probes
  # like /up from k8s LBs still fit easily. Tighten per-endpoint via
  # dedicated forwarders when needed.
  plug(SukhiFedi.Web.RateLimitPlug, bucket: "global", limit: 500, scale_ms: 60_000)
  plug(:match)

  plug(Plug.Parsers,
    parsers: [:json],
    json_decoder: Jason,
    body_reader: {SukhiFedi.Web.CacheBodyReader, :read_body, []}
  )

  plug(:dispatch)

  # ── ActivityPub / well-known (handled natively by Elixir) ────────────────

  get "/.well-known/webfinger" do
    WebfingerController.call(conn, [])
  end

  get "/users/:name" do
    ActorController.show(conn, [])
  end

  get "/users/:name/featured" do
    FeaturedController.show(conn, [])
  end

  get "/users/:name/followers" do
    CollectionController.followers(conn, [])
  end

  get "/users/:name/following" do
    CollectionController.following(conn, [])
  end

  get "/users/:name/outbox" do
    CollectionController.outbox(conn, [])
  end

  get "/users/:name/notes/:note_id" do
    NoteController.show(conn, [])
  end

  post "/users/:name/inbox" do
    InboxController.user_inbox(conn, [])
  end

  post "/inbox" do
    InboxController.shared_inbox(conn, [])
  end

  # ── NodeInfo (Elixir-native) ─────────────────────────────────────────────

  get "/.well-known/nodeinfo" do
    NodeinfoController.discovery(conn, [])
  end

  get "/nodeinfo/2.1" do
    NodeinfoController.v2_1(conn, [])
  end

  # ── Uploaded media ───────────────────────────────────────────────────────
  # Serves files written by `SukhiFedi.Addons.Media.create_from_upload/3`.
  # `MEDIA_DIR` env (default `priv/static/uploads`) controls the on-disk
  # root. Production should front this with a CDN.

  get "/uploads/*path" do
    serve_upload(conn, path)
  end

  # ── Human-facing HTML + JSON proxy for nodeinfo lookup ──────────────────

  get "/" do
    ViewerController.home(conn, [])
  end

  get "/api/nodeinfo" do
    ViewerController.nodeinfo_lookup(conn, [])
  end

  get "/api/watchers" do
    ViewerController.list_watchers(conn, [])
  end

  post "/api/watchers" do
    ViewerController.register_watcher(conn, [])
  end

  # SSE stream feeding the host-stats card on `/`. One JSON tick per second.
  get "/api/stats/stream" do
    StatsController.stream(conn, [])
  end

  # ── Health + metrics ─────────────────────────────────────────────────────

  get "/up" do
    send_resp(conn, 200, "ok")
  end

  get "/metrics" do
    PromEx.Plug.call(conn, PromEx.Plug.init(prom_ex_module: SukhiFedi.PromEx))
  end

  # ── Mastodon/Misskey REST API — dispatched to plugin nodes ───────────────
  #
  # `SukhiFedi.Web.PluginPlug` forwards the request to one of the plugin
  # Erlang nodes listed in `config :sukhi_fedi, :plugin_nodes`. Each
  # plugin node runs the `:sukhi_api` application (see the top-level
  # `api/` directory) and exposes capabilities via `:rpc`. If no plugin
  # node is reachable the client gets a 503.

  match "/api/v1/*_" do
    SukhiFedi.Web.PluginPlug.call(conn, SukhiFedi.Web.PluginPlug.init([]))
  end

  match "/api/admin/*_" do
    SukhiFedi.Web.PluginPlug.call(conn, SukhiFedi.Web.PluginPlug.init([]))
  end

  # OAuth 2.0 server endpoints (`/oauth/authorize`, `/oauth/token`,
  # `/oauth/revoke`) live on the api plugin node. PluginPlug is
  # path-agnostic so the same forwarder handles them.
  match "/oauth/*_" do
    SukhiFedi.Web.PluginPlug.call(conn, SukhiFedi.Web.PluginPlug.init([]))
  end

  match _ do
    send_resp(conn, 404, "not found")
  end

  # Path-traversal-safe static serve for `/uploads/<key>`. The key is
  # opaque random bytes generated by the upload pipeline so traversal
  # would only ever return 404, but we reject `..` components defensively.
  defp serve_upload(conn, path_segments) do
    if Enum.any?(path_segments, &(&1 == "..")) do
      send_resp(conn, 400, "")
    else
      root = media_dir()
      relative = Path.join(path_segments)
      full = Path.join(root, relative)

      cond do
        not String.starts_with?(Path.expand(full), Path.expand(root)) ->
          send_resp(conn, 400, "")

        File.regular?(full) ->
          ct = content_type_for(full)

          conn
          |> put_resp_content_type(ct)
          |> send_file(200, full)

        true ->
          send_resp(conn, 404, "")
      end
    end
  end

  defp media_dir do
    System.get_env("MEDIA_DIR") ||
      Path.join([:code.priv_dir(:sukhi_fedi), "static", "uploads"])
  end

  defp content_type_for(path) do
    case Path.extname(path) |> String.downcase() do
      ".png" -> "image/png"
      ".jpg" -> "image/jpeg"
      ".jpeg" -> "image/jpeg"
      ".gif" -> "image/gif"
      ".webp" -> "image/webp"
      ".mp4" -> "video/mp4"
      ".webm" -> "video/webm"
      ".mp3" -> "audio/mpeg"
      ".ogg" -> "audio/ogg"
      _ -> "application/octet-stream"
    end
  end
end
